### ISSUE TITLE
mongodb link

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-18#7]
`mongodb://heroku_xp4mmn13:cgegvnkqjbdtn5mmhne7jqh47u@ds229690.mlab.com:29690/heroku_xp4mmn13`

You'll need to have a loopback-connector-mongo package in order to setup it well.

Sample: https://github.com/GroceriStar/groceristar/blob/master/server/datasources.json

**Comment by atherdon** [comment]
this is a mongo link for you database. it's actually clean instance - that you can use without worries

**Comment by atherdon** [comment]
can we close this task?

**Comment by JorgeRodr** [comment]
@atherdon I would like to test if I did it right first. I will buzz you when I'm done.

**Comment by atherdon** [comment]
perfect!


On 29-May-2018 at 07:33 PM, JorgeRodr wrote:


@atherdon <https://github.com/atherdon> I would like to test if I did it
right first. I will buzz you when I'm done.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/loopback-tutor-intern-18/issues/7#issuecomment-392913995>,
or mute the thread

**Comment by JorgeRodr** [comment]
@atherdon You can close this task
