### ISSUE TITLE
move code to root folder

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-18#9]

**Comment by JorgeRodr** [comment]
Hi @atherdon , what is this about? I don't understand.

**Comment by atherdon** [comment]
just move files from reservation folder to repository root.


On 21-May-2018 at 10:44 AM, JorgeRodr wrote:


Hi @atherdon <https://github.com/atherdon> , what is this about? I don't
understand.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/loopback-tutor-intern-18/issues/9#issuecomment-390619635>,
or mute the thread
